sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'stable'
script:
- yarn install
- yarn build
after_success:
 - npm run semantic-release
